#!/bin/csh

echo "---------- deck0_random_test ----------"
run "rack-o,game,deck,card,hand,discard_pile" "deck0.txt" < "deck0_random_test.in" > "deck0_random_test.out"
dif deck0_random_test

echo "\n---------- deck1_draw_test ----------"
run "rack-o,game,deck,card,hand,discard_pile" "deck1.txt" < "deck1_draw_test.in" > "deck1_draw_test.out"
dif deck1_draw_test

echo "\n---------- deck1_nodraw_test ----------"
run "rack-o,game,deck,card,hand,discard_pile" "deck1.txt" < "deck1_nodraw_test.in" > "deck1_nodraw_test.out"
dif deck1_nodraw_test

echo "\n---------- deck1_discard_test ----------"
run "rack-o,game,deck,card,hand,discard_pile" "deck1.txt" < "deck1_discard_test.in" > "deck1_discard_test.out"
dif deck1_discard_test
