#!/bin/bash

testFolder="test"

# Get station and commands file names
stations="s$1"
commands="c$2"
combined="${stations}${commands}"
folder="${testFolder}/${combined}"
folderFile="${folder}/file"
folderTerm="${folder}/terminal"

# Get stations and commands files
stationsFile="${testFolder}/${stations}"
if [[ ! -f "$stationsFile" ]]; then
    echo "Error: $stationsFile does not exist!"
    exit 1
fi
commandsFile="${testFolder}/${commands}"
if [[ ! -f "$commandsFile" ]]; then
    echo "Error: $commandsFile does not exist!"
    exit 1
fi

# Get names for FILE outputs and references
outRefFile="${folderFile}/${combined}.out.ref"
stdOutRefFile="${folderFile}/${combined}.stdOut.ref"
stdErrRefFile="${folderFile}/${combined}.stdErr.ref"
outMeFile="${folderFile}/${combined}.out.me"
stdOutMeFile="${folderFile}/${combined}.stdOut.me"
stdErrMeFile="${folderFile}/${combined}.stdErr.me"
# Get names for TERMINAL outputs and references
outRefTerm="${folderTerm}/${combined}.out.ref"
stdOutRefTerm="${folderTerm}/${combined}.stdOut.ref"
stdErrRefTerm="${folderTerm}/${combined}.stdErr.ref"
outMeTerm="${folderTerm}/${combined}.out.me"
stdOutMeTerm="${folderTerm}/${combined}.stdOut.me"
stdErrMeTerm="${folderTerm}/${combined}.stdErr.me"


# Create directory
echo -e "Creating directories:"
mkdir -p ${folder}/file
mkdir -p ${folder}/terminal

# Create references
echo -e "\nCreating $outRefFile, $stdOutRefFile, and ${stdErrRefFile}:"
./the_MetroSim "$stationsFile" "$outRefFile" "$commandsFile" \
    > "$stdOutRefFile" 2> "$stdErrRefFile"
echo -e "\nCreating $outRefTerm, $stdOutRefTerm, and ${stdErrRefTerm}:"
./the_MetroSim "$stationsFile" "$outRefTerm" < "$commandsFile" \
    > "$stdOutRefTerm" 2> "$stdErrRefTerm"

# Compile me using make
echo -e "\nCompiling with make:"
make

# Create mes
echo -e "\nCreating $outMeFile, $stdOutMeFile, and ${stdErrMeFile}:"
./MetroSim "$stationsFile" "$outMeFile" "$commandsFile" \
    > "$stdOutMeFile" 2> "$stdErrMeFile" 
echo -e "\nCreating $outMeTerm, $stdOutMeTerm, and ${stdErrMeTerm}:"
./MetroSim "$stationsFile" "$outMeTerm" < "$commandsFile" \
    > "$stdOutMeTerm" 2> "$stdErrMeTerm" 

# File diffs
echo -e "\nRunning file diffs:"
echo -e "\n--- $outRefFile vs $outMeFile (file) ---\n"
diff "$outRefFile" "$outMeFile"
echo -e "\n\n--- $stdOutRefFile vs $stdOutMeFile (file) ---\n"
diff "$stdOutRefFile" "$stdOutMeFile"
echo -e "\n\n--- ${stdErrRefFile} vs $stdErrMeFile (file) ---\n"
diff "$stdErrRefFile" "$stdErrMeFile"

# Terminal diffs
echo -e "\nRunning terminal diffs:"
echo -e "\n--- $outRefTerm vs $outMeTerm (terminal) ---\n"
diff "$outRefTerm" "$outMeTerm"
echo -e "\n\n--- $stdOutRefTerm vs $stdOutMeTerm (terminal) ---\n"
diff "$stdOutRefTerm" "$stdOutMeTerm"
echo -e "\n\n--- ${stdErrRefTerm} vs $stdErrMeTerm (terminal) ---\n"
diff "$stdErrRefTerm" "$stdErrMeTerm"
